version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Porta que o frontend estará acessível

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db  # nome do serviço se
      - DB_PORT=5432  # Porta padrão do PostgreSQL
      - DB_USER=postgres  # Usuário do banco de dados
      - DB_PASSWORD=Numsey@2024  # Senha do banco de dados
      - DB_NAME=dtask_database  # Nome do banco de dados 
