version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=your_database_url
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DB_HOST=database  # nome do serviço
      - DB_PORT=5432  # Porta padrão do PostgreSQL
      - DB_USER=postgres  # Usuário do banco de dados
      - DB_PASSWORD=Numsey@2024  # Senha do banco de dados
      - DB_NAME=dtask_database  # Nome do banco de dados 